### ISSUE TITLE
Routing not possible due to "Uncaught TypeError: k.stations is not a function"

### ISSUE THREAD

**Issue by yannickoo** [derhuerst/vbb-map-routing#40] opened 2020-12-30 02:59 UTC
It seems like the autocomplete doesn't work atm because of this error

> `Uncaught TypeError: k.stations is not a function in bundle.js`

**Comment by derhuerst** [comment] 2020-12-30 19:24
Cannot reproduce it. Can you give more specific instructions how to make this error appear?

**Comment by derhuerst** [comment] 2021-04-13 21:28
I'm going to close this. Please re-open if you encounter this issue again.

**Closed by derhuerst** 2021-04-13 21:28 UTC
